/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.AddUser;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import user.User;

/**
 * This class provides the interface for the registration functionality.
 *
 * @author Promodi
 */
public class RegisterGUI extends javax.swing.JFrame {

    AddUser newUserAdd;

    /**
     * Creates new form Register
     */
    public RegisterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleRegister = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblConfirmPassword = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));

        mainPanel.setMaximumSize(new java.awt.Dimension(600, 600));
        mainPanel.setMinimumSize(new java.awt.Dimension(600, 600));
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 600));
        mainPanel.setLayout(null);

        titleRegister.setBackground(new java.awt.Color(255, 255, 255));
        titleRegister.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        titleRegister.setForeground(new java.awt.Color(255, 255, 255));
        titleRegister.setText("Register ");
        mainPanel.add(titleRegister);
        titleRegister.setBounds(200, 80, 206, 62);

        lblName.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");
        mainPanel.add(lblName);
        lblName.setBounds(190, 180, 34, 16);

        txtConfirmPassword.setPreferredSize(new java.awt.Dimension(70, 30));
        mainPanel.add(txtConfirmPassword);
        txtConfirmPassword.setBounds(190, 380, 230, 30);

        txtEmail.setPreferredSize(new java.awt.Dimension(70, 30));
        mainPanel.add(txtEmail);
        txtEmail.setBounds(190, 260, 230, 30);

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        mainPanel.add(lblEmail);
        lblEmail.setBounds(190, 240, 32, 16);

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        mainPanel.add(lblPassword);
        lblPassword.setBounds(190, 300, 56, 16);

        btnBack.setBackground(new java.awt.Color(119, 119, 119));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setPreferredSize(new java.awt.Dimension(100, 30));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        mainPanel.add(btnBack);
        btnBack.setBounds(190, 450, 100, 30);

        btnSignUp.setBackground(new java.awt.Color(153, 0, 255));
        btnSignUp.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign up");
        btnSignUp.setPreferredSize(new java.awt.Dimension(100, 30));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        mainPanel.add(btnSignUp);
        btnSignUp.setBounds(320, 450, 100, 30);

        btnExit.setBackground(new java.awt.Color(119, 119, 119));
        btnExit.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setPreferredSize(new java.awt.Dimension(100, 30));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        mainPanel.add(btnExit);
        btnExit.setBounds(260, 500, 100, 30);

        lblConfirmPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmPassword.setText(" Confirm Password");
        mainPanel.add(lblConfirmPassword);
        lblConfirmPassword.setBounds(190, 360, 106, 16);

        txtName.setPreferredSize(new java.awt.Dimension(70, 30));
        mainPanel.add(txtName);
        txtName.setBounds(190, 200, 230, 30);

        txtPassword.setPreferredSize(new java.awt.Dimension(70, 30));
        mainPanel.add(txtPassword);
        txtPassword.setBounds(190, 320, 230, 30);

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_img.jpeg"))); // NOI18N
        background.setAlignmentY(0.0F);
        background.setMaximumSize(new java.awt.Dimension(600, 600));
        background.setMinimumSize(new java.awt.Dimension(600, 600));
        background.setPreferredSize(new java.awt.Dimension(600, 600));
        mainPanel.add(background);
        background.setBounds(0, 0, 600, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        HomeGUI push = new HomeGUI();
        push.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        String reg = "^[A-Za-z0-9+_.-]+@(.+)$";
        Pattern pat = Pattern.compile(reg);

        String name = txtName.getText();
        String email = txtEmail.getText();
        Matcher match = pat.matcher(email);

        char[] password = txtConfirmPassword.getPassword();
        char[] confirmPassword = txtPassword.getPassword();

        String passwordStr = Arrays.toString(password);
        String ConfirmPassStr = Arrays.toString(confirmPassword);

        User user = new User(name, email, passwordStr);
        newUserAdd = new AddUser();

        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the Name");
        } else if (email.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the Email address");
        } else if (!match.matches()) {
            JOptionPane.showMessageDialog(null, "Please enter Valid Email address");
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the Password");
        } else if (passwordStr.length() < 8) {
            JOptionPane.showMessageDialog(this, "Enter a password with 8 charactors");
        } else if (confirmPassword.equals("")) {
            JOptionPane.showMessageDialog(this, "Please confirm the password");
        } else if (ConfirmPassStr.length() < 8) {
            JOptionPane.showMessageDialog(this, "Enter a password with 8 charactors");
        } else {
            if (newUserAdd.newUserAdd(user.getName(), user.getEmail(), user.getPassword(), ConfirmPassStr)) {
                JOptionPane.showMessageDialog(this, "Registered Succesfully");

                this.dispose();
                LoginGUI push = new LoginGUI();
                push.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Registration failed");
                txtConfirmPassword.setText("");
                txtPassword.setText("");
            }
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel titleRegister;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
